### PR TITLE
Issue #1507 - Selective sync is broken in UI

### LINKED ISSUE #1498: Resources on sync panel and not sorted
**Describe the bug**
The resources list on application sync panel is not sorted. Everytime any application resource changes the list order changes which makes it difficult to use UI

**To Reproduce**
1. Go to any application details
2. Click on 'Sync' button
3. See the unsorted list

**Expected behavior**
Resources must be sorted.

### LINKED ISSUE #1507: Selective sync is broken in UI
**Describe the bug**
UI is triggering full sync even if a single resource is selected on sync app panel.

**To Reproduce**
1. Deploy any app which has more than one resources
2. Click on 'Sync' button and select one resource.
3. See the full sync is triggered.

**Expected behavior**
Only selected resource must be synced.

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/1507
Closes https://github.com/argoproj/argo-cd/issues/1498

### CODE REVIEW

File: src/app/applications/components/application-sync-panel/application-sync-panel.tsx [hunk 1]
```diff
@@ -15,9 +15,8 @@ export const ApplicationSyncPanel = ({application, selectedResource, hide}: {
 
     const [form, setForm] = React.useState<FormApi>(null);
     const isVisible = !!(selectedResource && application);
-    const syncResIndex = application && selectedResource && application.status.resources.findIndex((item) => {
-        return nodeKey(item) === selectedResource;
-    });
+    const appResources = (application && selectedResource && application.status.resources || []).sort((first, second) => nodeKey(first).localeCompare(nodeKey(second)));
```
Comment (alexec) [inline src/app/applications/components/application-sync-panel/application-sync-panel.tsx]: I think you also want `&& application.status`

**Review by alexec — APPROVED** [review]
One comment.

File: src/app/applications/components/application-sync-panel/application-sync-panel.tsx (hunk 1 above)
Comment (alexmt) [reply src/app/applications/components/application-sync-panel/application-sync-panel.tsx]: you are right. Thank you!
